upstream django_v1 {
    server web_django:8000;
}

upstream flask_v2 {
    server pagos_flask:5000;
}

server {
    listen 80;

    # Django (v1)
    location /api/v1/ {
        proxy_pass http://django_v1;
        proxy_set_header Host $host;
    }

    # Flask (v2)  ← CORREGIDO
    location /api/v2/ {
        proxy_pass http://flask_v2;
        proxy_set_header Host $host;
    }
}